import Vue from 'vue'
import CarbonComponentsVue from '@carbon/vue'

Vue.use(CarbonComponentsVue, [
    'CvButton',
    'CvButtonSkeleton',
    'CvCodeSnippet',
    'CvCodeSnippetSkeleton',
    'CvContent',
    'CvDataTable',
    'CvDataTableSkeleton',
    'CvForm',
    'CvHeader',
    'CvHeaderGlobalAction',
    'CvHeaderMenuButton',
    'CvHeaderMenuItem',
    'CvHeaderName',
    'CvHeaderNav',
    'CvHeaderSideNavItems',
    'CvInlineNotification',
    'CvNumberInput',
    'CvRadioButton',
    'CvRadioGroup',
    'CvSkipToContent',
    'CvSideNav',
    'CvSideNavItems',
    'CvSideNavLink',
    'CvSideNavMenu',
    'CvSideNavMenuItem',
    'CvSkeletonText',
    'CvTag',
    'CvTextInput',
    'CvToastNotification',
])
