version: '3.8'
services:
    
    decarb_db:
        image: postgres:13.2
        container_name: decarb_postgres
        environment:
          - POSTGRES_DB=decarb
          - POSTGRES_USER=api
          - POSTGRES_PASSWORD=!ChangeMe!
        restart: "unless-stopped"
        volumes:
          - postgres:/var/lib/postgresql/decarb/data
        ports:
          - "5432:5432"

    decarb_db_admin:
        image: adminer:4
        container_name: decarb_adminer
        restart: "unless-stopped"
        depends_on:
          - decarb_db
        ports:
          - 5080:8080
volumes:
    postgres:

