name: Stage Deployment Workflow
on:
  push:
    branches: [ stage ]

jobs:
  deploy:
    name: Stage Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploying to Stage Server via SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: centaurus.uberspace.de
        username: decarb
        key: ${{ secrets.DECARB_STAGE_SECRET }}
        port: 22
        script: |
          sh /var/www/virtual/decarb/deploy-stage.sh
